spring.application.name=agendador-horarios

spring.datasource.url=jdbc:h2:mem:agendamentos-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enable=true
spring.hs.console.path=/h2-console

# Nível de log (reduz ruído)
logging.level.root=WARN
logging.level.com.estudo=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Padrão mais limpo e colorido
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(${PID}){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n